"""
Validator — Stage 3 of the pipeline.

Sends high-confidence hypotheses (from the screener) to an expensive model
(default: claude-sonnet-4-6) for deep analysis.

Performs:
  1. Full attack-path tracing
  2. Working PoC generation
  3. CVSS 4.0 scoring
  4. Devil's Advocate rebuttal + response
  5. Mitigation recommendations
"""

from __future__ import annotations

import json
import os
import time
from typing import Optional

import anthropic

from pipeline.models import Severity, ValidationResult, VulnHypothesis

VALIDATE_MODEL = os.getenv("VALIDATE_MODEL", "claude-sonnet-4-6")
MAX_RETRIES = 3
RETRY_DELAY = 10


_SYSTEM_PROMPT = """\
You are a world-class offensive security researcher and CVE hunter.
You receive a vulnerability hypothesis generated by a screening model and must perform a rigorous deep analysis.

Your analysis must cover:
1. **Attack Path**: Step-by-step trace from attacker-controlled input to the vulnerable code.
2. **PoC Code**: A minimal, working proof-of-concept (Python preferred). If a live server is needed, simulate with an in-process test.
3. **CVSS 4.0 Score**: Score and vector string.
4. **Devil's Advocate**: State the strongest 2-3 reasons why this might NOT be a real vulnerability (preconditions, scope limitations, etc.).
5. **DA Response**: Counter-argument showing why the vulnerability is still valid despite the rebuttal.
6. **Severity**: Critical / High / Medium / Low
7. **Confirmed**: true if exploitable in realistic conditions, false otherwise.
8. **Mitigation**: Specific code-level fix.

Output ONLY valid JSON (no markdown, no preamble):
{
  "confirmed": true,
  "severity": "High",
  "cvss_score": 7.5,
  "cvss_vector": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N",
  "attack_path": "...",
  "poc_code": "...",
  "da_rebuttal": "...",
  "da_response": "...",
  "mitigation": "..."
}"""


def _severity_from_str(s: str) -> Severity:
    mapping = {
        "critical": Severity.CRITICAL,
        "high": Severity.HIGH,
        "medium": Severity.MEDIUM,
        "low": Severity.LOW,
    }
    return mapping.get(s.lower(), Severity.INFO)


def _call_validator(
    client: anthropic.Anthropic,
    hypothesis: VulnHypothesis,
) -> ValidationResult:
    chunk = hypothesis.chunk
    user_msg = (
        f"## Vulnerability Hypothesis\n"
        f"**Type:** {hypothesis.vuln_type}\n"
        f"**Confidence (screener):** {hypothesis.confidence}/10\n"
        f"**Description:** {hypothesis.description}\n"
        f"**Location:** {hypothesis.location_hint} in `{chunk.name}` ({chunk.file_path}:{chunk.start_line})\n"
        f"**Screener reasoning:** {hypothesis.reasoning}\n\n"
        f"## Code Under Analysis\n\n"
        + chunk.to_prompt_block()
    )

    for attempt in range(MAX_RETRIES):
        try:
            response = client.messages.create(
                model=VALIDATE_MODEL,
                max_tokens=4096,
                system=[
                    {
                        "type": "text",
                        "text": _SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                messages=[{"role": "user", "content": user_msg}],
            )
            break
        except anthropic.RateLimitError:
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_DELAY * (attempt + 1))
            else:
                raise
        except anthropic.APIError as exc:
            raise RuntimeError(f"Validator API error: {exc}") from exc

    raw = response.content[0].text.strip()

    if raw.startswith("```"):
        raw = raw.split("```", 2)[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.rsplit("```", 1)[0]

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        # Return unconfirmed result on parse failure
        return ValidationResult(
            hypothesis=hypothesis,
            confirmed=False,
            severity=Severity.INFO,
            cvss_score=0.0,
            attack_path="(parse error)",
            poc_code="",
            da_rebuttal="",
            da_response="",
            mitigation="",
            validator_model=VALIDATE_MODEL,
            raw_response=raw,
        )

    return ValidationResult(
        hypothesis=hypothesis,
        confirmed=bool(data.get("confirmed", False)),
        severity=_severity_from_str(data.get("severity", "informational")),
        cvss_score=float(data.get("cvss_score", 0.0)),
        attack_path=data.get("attack_path", ""),
        poc_code=data.get("poc_code", ""),
        da_rebuttal=data.get("da_rebuttal", ""),
        da_response=data.get("da_response", ""),
        mitigation=data.get("mitigation", ""),
        validator_model=VALIDATE_MODEL,
        raw_response=raw,
    )


def validate_hypotheses(
    hypotheses: list[VulnHypothesis],
    api_key: Optional[str] = None,
    verbose: bool = False,
) -> list[ValidationResult]:
    """
    Deeply validate each hypothesis with the expensive model.
    Returns all results (confirmed and unconfirmed).
    """
    client = anthropic.Anthropic(api_key=api_key or os.getenv("ANTHROPIC_API_KEY"))
    results: list[ValidationResult] = []

    for i, hyp in enumerate(hypotheses, 1):
        if verbose:
            print(f"  [{i}/{len(hypotheses)}] validating [{hyp.confidence:.1f}] {hyp.vuln_type} in {hyp.chunk.name}")

        result = _call_validator(client, hyp)
        results.append(result)

        if verbose:
            verdict = "CONFIRMED" if result.confirmed else "false positive"
            print(f"    -> {verdict} | CVSS {result.cvss_score} ({result.severity.value})")

    return results
